server:
  port: 8081
  tomcat:
    uri-encoding: UTF-8
    max-threads: 200
    accept-count: 200
    min-spare-threads: 50

# 异步线程配置
async:
  executor:
    thread:
# 配置核心线程数
      core_pool_size: 5
# 配置最大线程数
      max_pool_size: 5
# 配置队列大小
      queue_capacity: 99999
# 配置线程池中的线程的名称前缀
      name.prefix: async-service-





